baseURL = 'http://coruscant.space-4.de/'
languageCode = 'de-de'
title = 'Coruscant'
theme = "coruscant"

# Main menu
# pageRef => Needed for Highliting the Active Nav-Item
# Parent => Determines the parent-nav-item. Needs to be 'Name' of parent

[menu]
  [[menu.main]]
    name = "SP4"
    weight = 10
  [[menu.main]]
    pageRef = "/"
    name = "Home"
    pre = "home"
    url = "/"
    weight = 15
    parent = "SP4"
  [[menu.main]]
    pageRef = "portfolio"
    name = "Portfolio"
    pre = "portfolio"
    url = "/portfolio"
    weight = 16
    parent = "SP4"

  [[menu.main]]
    name = "Services"
    weight = 20
  [[menu.main]]
    pageRef="uiux-design"
    name = "Ui/Ux Design"
    pre = "uiux"
    url = "/uiux"
    weight = 25
    parent = "Services"
  [[menu.main]]
    pageRef="webdevelopment"
    name = "Web Development"
    pre = "webdevelopment"
    url = "/webdevelopment"
    weight = 26
    parent = "Services"
  [[menu.main]]
    pageRef="onlinemarketing"
    name = "Online Marketing"
    pre = "onlinemarketing"
    url = "/online-marketing"
    weight = 27
    parent = "Services"

  [[menu.main]]
    pageRef="about"
    name = "About"
    weight = 30
    parent = ""
  [[menu.main]]
    pageRef="career"
    name = "Jobs, Jobs, Jobs"
    pre = "career"
    url = "/career"
    weight = 35
    parent = "About"
  [[menu.main]]
    pageRef="resources"
    name = "Resources"
    pre = "resources"
    url = "/resources"
    weight = 35
    parent = "About"
  [[menu.main]]
    pageRef="coruscant"
    name = "Coruscant"
    pre = "coruscant"
    url = "/coruscant"
    weight = 36
    parent = "About"


# Some Instructions to Help Hugo find Bootstrap Stuff and Render them to Public when 'Hugo'
[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "static/js/bootstrap.bundle.min.js"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/css/bootstrap.min.css"
    target = "static/css/bootstrap.min.css"