baseURL = 'http://coruscant.space-4.de/'
languageCode = 'de-de'
title = 'Coruscant'
theme = "coruscant"

# Main menu
# pageRef => Needed for Highliting the Active Nav-Item

[menu]
  [[menu.main]]
    pageRef="/"
    name = "Home"
    pre = "home"
    url = "/"
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = "Posts"
    pre = "pen-tool"
    url = "https://www.google.de"
    weight = 20
  [[menu.main]]
    pageRef="facebook"
    name = "Facebook"
    pre = "facebook"
    url = "https://www.facebook.de"
    weight = 25
    parent = "Posts"
  [[menu.main]]
    pageRef="facebook"
    name = "Alibaba"
    pre = "facebook"
    url = "https://www.facebook.de"
    weight = 26
    parent = "Posts"
  [[menu.main]]
    pageRef="tags"
    name = "Tags"
    pre = "tag"
    url = "https://www.google.de"
    weight = 30
[[menu.main]]
    pageRef="test2"
    name = "Test2"
    pre = "test2"
    url = "https://www.google.de"
    weight = 40
  [[menu.main]]
    pageRef="test3"
    name = "Test3"
    pre = "test3"
    url = "https://www.facebook.de"
    weight = 41
    parent = "Test2"
  [[menu.main]]
    pageRef="test4"
    name = "Test4"
    pre = "test4"
    url = "https://www.facebook.de"
    weight = 42
    parent = "Test2"

# Some Instructions to Help Hugo find Bootstrap Stuff and Render them to Public when 'Hugo'
[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "static/js/bootstrap.bundle.min.js"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/css/bootstrap.min.css"
    target = "static/css/bootstrap.min.css"